# .pre-commit-config.yaml
# Pre-commit hooks for Datatrack CLI project (Python)

repos:

  # 1. Autoformat Python code with Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # 1b. Enforce spacing between functions (pyupgrade + trailing comma)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--keep-percent-format, --py38-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  # 2. Linting with Ruff (faster alternative to flake8, pylint, etc.)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--fix]  # auto-fixes common issues

  # 3. Sort Python imports with isort
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort (import sorter)

  # 4. Common file hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
